---
apiVersion: v1
kind: Service
metadata:
  name: foo-svc
  labels:
    app: foo-app
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30090
  selector:
    app: foo-app
  type: NodePort
