---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-pod-status
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pod-status-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read-pod-status
subjects:
- kind: ServiceAccount
  name: read-pod-status-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: read-pod-status-sa
  namespace: default
# automountServiceAccountToken: false