apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-foo
spec:
  replicas: 10
  strategy:
    canary:
      analysis:
        templates:
        - templateName: analysis-webcheck
        args:
        - name: pod-hash
          valueFrom:
            podTemplateHashValue: Latest
        startingStep: 2 # delay starting analysis run 
      steps:
      - setWeight: 10
      - pause: {duration: 10s}
      - setWeight: 20
      - pause: {duration: 10s}
      - setWeight: 30
      - pause: {duration: 10s}
      - setWeight: 40
      - pause: {duration: 10s}
      - setWeight: 50
      - pause: {duration: 10s}
      - setWeight: 60
      - pause: {duration: 10s}
      - setWeight: 70
      - pause: {duration: 10s}
      - setWeight: 80
      - pause: {duration: 10s}
      - setWeight: 90
      - pause: {duration: 10s}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: rollouts-foo
  template:
    metadata:
      labels:
        app: rollouts-foo
    spec:
      containers:
      - image: public.ecr.aws/i4a3l2a7/probeserver:latest
        name: foo
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
          - name: HEALTH_STATUS_FACTOR
            value: '0'
          - name: CONTENT
            value: '{ "version": "1.0.0" }'
